### ISSUE TITLE
Roadmap with planned future features

### ISSUE THREAD

**Issue by Automaticism** [Automaticism/Promptvision#20]
# Roadmap
## Initial Release 21.3.23
Our first release on March 21st, 2023 marked the beginning of our journey. We were excited to introduce our product to the world, and our team worked hard to ensure that the initial release was a success.

## Rewrote Navigation to Use Requests 24.3.23
Just three days later, on March 24th, we made significant improvements to the navigation system. We replaced the old system with the latest requests technology, improving the overall user experience and making it easier to navigate through our application.

## Extended Version 3.4.23
On April 3rd, we released an extended version of our application that included a range of new features and improvements. We added support for JPG images, rewrote our EXIF parsing functionality, improved our regex system, and tightened up the UI.

## Aesthetic Score 4.4.23
Just one day later, on April 4th, we released an exciting new feature that we're confident our users will love. We added an aesthetic score to our application, allowing users to measure the beauty of their images.

---
`(^ roadmap generated by ChatGPT)`

## Looking Ahead
- [ ] Moving / copying / deleting /  renaming utility functions
- [x] Analyzing prompts and extracting data (the reason behind the project and its name, **Prompt**vision)

The last point is the main point that I will be focusing my effort on in the future. 
The groundwork is done. Metadata and exif parsing are there. What's left is tying it together to be able to browse and extract prompt knowledge that will help you create even better prompts that will give you exactly what you are looking for. This project was originally inspired by multiple things, but one paper did inspire me more; [Hard Prompts Made Easy: Gradient-Based Discrete Optimization for Prompt Tuning and Discovery](https://arxiv.org/abs/2302.03668)
Of course we could just analyze the models directly and so on, but this approach is more of a discovery based way of finding your _hard_ prompts that generate the results you are looking for. 

I am currently either thinking of using Streamlit or Panel to visualize the data that this image viewer generates. This will enable dynamic analysis of all the data by having adjustable dashboards where you can pick and adjust which parameters that should be used to filter out what you want. E.g. adjust to see all images with aesthetic score > 5 where the prompts have "carrot" in them. 

There are many possibilities for things that can be done with this. At the top of my head I have ideas such as filtering out all your favourites with atleast 4 stars, do fuzzy matching on their prompts, extract different clusters of prompts and do NLP analysis on the prompts. It isn't a hard task, it's just that a project such as this has so many nuances you can spend much time on such as design, QoL features and so on.

**Comment by Automaticism** [comment]
- [ ] Refresh button that will update metadata and such without restarting the gallery
- [ ] Save favourites to a favourites directory
- [x] NLP analyze prompts
- [ ] Export prompts to <tool>(such as dynamic prompts)
- [ ] SD WebUI API send-to [controlnet | img2img | ... ]
- [ ] Improve thumbnails so that browsing becomes more pleasant

**Comment by dshipley71** [comment]
A couple suggestions:

1.) Both Streamlit and Panel are good options, but I would go with Streamlit. It is more focused on developing dashboards. I moved from Dash/Plotly and haven't look back myself on projects. You can also integrate JavaScript's as Streamlit components to take advantage of already developed tools/libraries.

2a.) Instead of using piexif library (which appears to be last updated in 2019), consider using EXIFTOOL. It is continuously updated. Although the core of EXIFTOOL is Perl, there is a python wrapper for it. It is great especially for uncommon exif tags such as "UserComment" - for this tag specifically, piexif did not like it and would not extract tags successfully using this tool.

2b.) If you do not want to use EXIFTOOL, you could use Pillow's ExifTags capabilities. Similar to above, and since this project uses Pillow, you could eliminate the additional dependency on piexif.

**Comment by Automaticism** [comment]
I've started working on porting this over to using Streamlit as the UI.
Currently I have a working solution that loads up a directory (and all sub directories), with browsing the images and seeing the information.
 
I've unfortunately been under the weather and a lack of motivation has delayed further developments.

Currently done parts:
- Thumbnails
- Browsing
- Directory support
- Prompt analysis - clustering, levenstein distance, intent, and a few more. This is basically only limited by the imagination (and the NLP frameworks that exist)

To be implemented:
- Form for setting rating, favorite, tag and categorizes (I have the rough implementation idea, additionally with multi-select support)
- Deletion, moving, copying -- utility functions
- Option to load in the exif & metadata csv instead of inserting a directory
